export const countryList = [
  {value: "Afghanistan", displayValue: "Afghanistan"},
  {value: "Albania", displayValue: "Albania"},
  {value: "Algeria", displayValue: "Algeria"},
  {value: "Andorra", displayValue: "Andorra"},
  {value: "Angola", displayValue: "Angola"},
  {value: "Antigua & Deps", displayValue: "Antigua & Deps"},
  {value: "Argentina", displayValue: "Argentina"},
  {value: "Armenia", displayValue: "Armenia"},
  {value: "Australia", displayValue: "Australia"},
  {value: "Austria", displayValue: "Austria"},
  {value: "Azerbaijan", displayValue: "Azerbaijan"},
  {value: "Bahamas", displayValue: "Bahamas"},
  {value: "Bahrain", displayValue: "Bahrain"},
  {value: "Bangladesh", displayValue: "Bangladesh"},
  {value: "Barbados", displayValue: "Barbados"},
  {value: "Belarus", displayValue: "Belarus"},
  {value: "Belgium", displayValue: "Belgium"},
  {value: "Belize", displayValue: "Belize"},
  {value: "Benin", displayValue: "Benin"},
  {value: "Bhutan", displayValue: "Bhutan"},
  {value: "Bolivia", displayValue: "Bolivia"},
  {value: "Bosnia Herzegovina", displayValue: "Bosnia Herzegovina"},
  {value: "Botswana", displayValue: "Botswana"},
  {value: "Brazil", displayValue: "Brazil"},
  {value: "Brunei", displayValue: "Brunei"},
  {value: "Bulgaria", displayValue: "Bulgaria"},
  {value: "Burkina", displayValue: "Burkina"},
  {value: "Burundi", displayValue: "Burundi"},
  {value: "Cambodia", displayValue: "Cambodia"},
  {value: "Cameroon", displayValue: "Cameroon"},
  {value: "Canada", displayValue: "Canada"},
  {value: "Cape Verde", displayValue: "Cape Verde"},
  {value: "Central African Rep", displayValue: "Central African Rep"},
  {value: "Chad", displayValue: "Chad"},
  {value: "Chile", displayValue: "Chile"},
  {value: "China", displayValue: "China"},
  {value: "Colombia", displayValue: "Colombia"},
  {value: "Comoros", displayValue: "Comoros"},
  {value: "Congo", displayValue: "Congo"},
  {value: "Congo Democratic Rep", displayValue: "Congo Democratic Rep}"},
  {value: "Costa Rica", displayValue: "Costa Rica"},
  {value: "Croatia", displayValue: "Croatia"},
  {value: "Cuba", displayValue: "Cuba"},
  {value: "Cyprus", displayValue: "Cyprus"},
  {value: "Czech Republic", displayValue: "Czech Republic"},
  {value: "Denmark", displayValue: "Denmark"},
  {value: "Djibouti", displayValue: "Djibouti"},
  {value: "Dominica", displayValue: "Dominica"},
  {value: "Dominican Republic", displayValue: "Dominican Republic"},
  {value: "East Timor", displayValue: "East Timor"},
  {value: "Ecuador", displayValue: "Ecuador"},
  {value: "Egypt", displayValue: "Egypt"},
  {value: "El Salvador", displayValue: "El Salvador"},
  {value: "Equatorial Guinea", displayValue: "Equatorial Guinea"},
  {value: "Eritrea", displayValue: "Eritrea"},
  {value: "Estonia", displayValue: "Estonia"},
  {value: "Ethiopia", displayValue: "Ethiopia"},
  {value: "Fiji", displayValue: "Fiji"},
  {value: "Finland", displayValue: "Finland"},
  {value: "France", displayValue: "France"},
  {value: "Gabon", displayValue: "Gabon"},
  {value: "Gambia", displayValue: "Gambia"},
  {value: "Georgia", displayValue: "Georgia"},
  {value: "Germany", displayValue: "Germany"},
  {value: "Ghana", displayValue: "Ghana"},
  {value: "Greece", displayValue: "Greece"},
  {value: "Grenada", displayValue: "Grenada"},
  {value: "Guatemala", displayValue: "Guatemala"},
  {value: "Guinea", displayValue: "Guinea"},
  {value: "Guinea-Bissau", displayValue: "Guinea-Bissau"},
  {value: "Guyana", displayValue: "Guyana"},
  {value: "Haiti", displayValue: "Haiti"},
  {value: "Honduras", displayValue: "Honduras"},
  {value: "Hungary", displayValue: "Hungary"},
  {value: "Iceland", displayValue: "Iceland"},
  {value: "India", displayValue: "India"},
  {value: "Indonesia", displayValue: "Indonesia"},
  {value: "Iran", displayValue: "Iran"},
  {value: "Iraq", displayValue: "Iraq"},
  {value: "Ireland", displayValue: "Ireland"},
  {value: "Israel", displayValue: "Israel"},
  {value: "Italy", displayValue: "Italy"},
  {value: "Ivory Coast", displayValue: "Ivory Coast"},
  {value: "Jamaica", displayValue: "Jamaica"},
  {value: "Japan", displayValue: "Japan"},
  {value: "Jordan", displayValue: "Jordan"},
  {value: "Kazakhstan", displayValue: "Kazakhstan"},
  {value: "Kenya", displayValue: "Kenya"},
  {value: "Kiribati", displayValue: "Kiribati"},
  {value: "Korea North", displayValue: "Korea North"},
  {value: "Korea South", displayValue: "Korea South"},
  {value: "Kosovo", displayValue: "Kosovo"},
  {value: "Kuwait", displayValue: "Kuwait"},
  {value: "Kyrgyzstan", displayValue: "Kyrgyzstan"},
  {value: "Laos", displayValue: "Laos"},
  {value: "Latvia", displayValue: "Latvia"},
  {value: "Lebanon", displayValue: "Lebanon"},
  {value: "Lesotho", displayValue: "Lesotho"},
  {value: "Liberia", displayValue: "Liberia"},
  {value: "Libya", displayValue: "Libya"},
  {value: "Liechtenstein", displayValue: "Liechtenstein"},
  {value: "Lithuania", displayValue: "Lithuania"},
  {value: "Luxembourg", displayValue: "Luxembourg"},
  {value: "Macedonia", displayValue: "Macedonia"},
  {value: "Madagascar", displayValue: "Madagascar"},
  {value: "Malawi", displayValue: "Malawi"},
  {value: "Malaysia", displayValue: "Malaysia"},
  {value: "Maldives", displayValue: "Maldives"},
  {value: "Mali", displayValue: "Mali"},
  {value: "Malta", displayValue: "Malta"},
  {value: "Marshall Islands", displayValue: "Marshall Islands"},
  {value: "Mauritania", displayValue: "Mauritania"},
  {value: "Mauritius", displayValue: "Mauritius"},
  {value: "Mexico", displayValue: "Mexico"},
  {value: "Micronesia", displayValue: "Micronesia"},
  {value: "Moldova", displayValue: "Moldova"},
  {value: "Monaco", displayValue: "Monaco"},
  {value: "Mongolia", displayValue: "Mongolia"},
  {value: "Montenegro", displayValue: "Montenegro"},
  {value: "Morocco", displayValue: "Morocco"},
  {value: "Mozambique", displayValue: "Mozambique"},
  {value: "Myanmar", displayValue: "Myanmar"},
  {value: "Namibia", displayValue: "Namibia"},
  {value: "Nauru", displayValue: "Nauru"},
  {value: "Nepal", displayValue: "Nepal"},
  {value: "Netherlands", displayValue: "Netherlands"},
  {value: "New Zealand", displayValue: "New Zealand"},
  {value: "Nicaragua", displayValue: "Nicaragua"},
  {value: "Niger", displayValue: "Niger"},
  {value: "Nigeria", displayValue: "Nigeria"},
  {value: "Norway", displayValue: "Norway"},
  {value: "Oman", displayValue: "Oman"},
  {value: "Pakistan", displayValue: "Pakistan"},
  {value: "Palau", displayValue: "Palau"},
  {value: "Panama", displayValue: "Panama"},
  {value: "Papua New Guinea", displayValue: "Papua New Guinea"},
  {value: "Paraguay", displayValue: "Paraguay"},
  {value: "Peru", displayValue: "Peru"},
  {value: "Philippines", displayValue: "Philippines"},
  {value: "Poland", displayValue: "Poland"},
  {value: "Portugal", displayValue: "Portugal"},
  {value: "Qatar", displayValue: "Qatar"},
  {value: "Romania", displayValue: "Romania"},
  {value: "Russian Federation", displayValue: "Russian Federation"},
  {value: "Rwanda", displayValue: "Rwanda"},
  {value: "St Kitts & Nevis", displayValue: "St Kitts & Nevis"},
  {value: "St Lucia", displayValue: "St Lucia"},
  {value: "Saint Vincent & the Grenadines", displayValue: "Saint Vincent & the Grenadines"},
  {value: "Samoa", displayValue: "Samoa"},
  {value: "San Marino", displayValue: "San Marino"},
  {value: "Sao Tome & Principe", displayValue: "Sao Tome & Principe"},
  {value: "Saudi Arabia", displayValue: "Saudi Arabia"},
  {value: "Senegal", displayValue: "Senegal"},
  {value: "Serbia", displayValue: "Serbia"},
  {value: "Seychelles", displayValue: "Seychelles"},
  {value: "Sierra Leone", displayValue: "Sierra Leone"},
  {value: "Singapore", displayValue: "Singapore"},
  {value: "Slovakia", displayValue: "Slovakia"},
  {value: "Slovenia", displayValue: "Slovenia"},
  {value: "Solomon Islands", displayValue: "Solomon Islands"},
  {value: "Somalia", displayValue: "Somalia"},
  {value: "South Africa", displayValue: "South Africa"},
  {value: "South Sudan", displayValue: "South Sudan"},
  {value: "Spain", displayValue: "Spain"},
  {value: "Sri Lanka", displayValue: "Sri Lanka"},
  {value: "Sudan", displayValue: "Sudan"},
  {value: "Suriname", displayValue: "Suriname"},
  {value: "Swaziland", displayValue: "Swaziland"},
  {value: "Sweden", displayValue: "Sweden"},
  {value: "Switzerland", displayValue: "Switzerland"},
  {value: "Syria", displayValue: "Syria"},
  {value: "Taiwan", displayValue: "Taiwan"},
  {value: "Tajikistan", displayValue: "Tajikistan"},
  {value: "Tanzania", displayValue: "Tanzania"},
  {value: "Thailand", displayValue: "Thailand"},
  {value: "Togo", displayValue: "Togo"},
  {value: "Tonga", displayValue: "Tonga"},
  {value: "Trinidad & Tobago", displayValue: "Trinidad & Tobago"},
  {value: "Tunisia", displayValue: "Tunisia"},
  {value: "Turkey", displayValue: "Turkey"},
  {value: "Turkmenistan", displayValue: "Turkmenistan"},
  {value: "Tuvalu", displayValue: "Tuvalu"},
  {value: "Uganda", displayValue: "Uganda"},
  {value: "Ukraine", displayValue: "Ukraine"},
  {value: "United Arab Emirates", displayValue: "United Arab Emirates"},
  {value: "United Kingdom", displayValue: "United Kingdom"},
  {value: "United States", displayValue: "United States"},
  {value: "Uruguay", displayValue: "Uruguay"},
  {value: "Uzbekistan", displayValue: "Uzbekistan"},
  {value: "Vanuatu", displayValue: "Vanuatu"},
  {value: "Vatican City", displayValue: "Vatican City"},
  {value: "Venezuela", displayValue: "Venezuela"},
  {value: "Vietnam", displayValue: "Vietnam"},
  {value: "Yemen", displayValue: "Yemen"},
  {value: "Zambia", displayValue: "Zambia"},
  {value: "Zimbabwe", displayValue: "Zimbabwe"},
]
